 autoenc1 = trainAutoencoder(trainfea,300, ...
    'MaxEpochs',32, ...
    'L2WeightRegularization',0.4, ...
    'SparsityRegularization',8, ...
    'SparsityProportion',0.5, ...
    'ScaleData', true);

feat1 = encode(autoenc1,trainfea);


autoenc2 = trainAutoencoder(feat1,150, ...
    'MaxEpochs',22, ...
    'L2WeightRegularization',0.2, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.1, ...
    'ScaleData', true);

feat2 = encode(autoenc2,feat1);
softnet = trainSoftmaxLayer(feat2,traintarg,'LossFunction','crossentropy');
%softnet = trainSoftmaxLayer(feat2,result,'LossFunction','crossentropy');
deepnet = stack(autoenc1,autoenc2,softnet);
[deepnet, tr]= train(deepnet,trainfea,traintarg);
ye=deepnet(testfea);
plotconfusion(testtarg, ye);
%plottrainstate(tr);
%plotperform(tr);